version: '3.8'

services:
    api:
        build: .
        command: ["python", "-m", "src"]
        env_file:
            - ./configs/api/default
            - ./configs/api/override
        profiles:
            - development
        networks:
            - dev_postgres
        depends_on:
            - dev_postgres
    
    tests:
        build: .
        command: ["pytest", "--color=yes", "-vv", "--tb=short", "-l", "--capture=sys", "src"]
        env_file:
            - ./configs/api/test
        profiles:
            - testing
        networks:
            - dev_postgres
        depends_on:
            - dev_postgres


    dev_postgres:
        image: postgres:latest
        env_file:
            - ./configs/postgres/default
        expose:
            - 5432
        networks:
            - dev_postgres
        profiles:
            - testing
            - development

networks:
    dev_postgres: