version: '3.8'

services:
    api:
        build: .
        command: ["python", "-m", "src"]
        env_file:
            - ./configs/api/default
            - ./configs/api/override
        profiles:
            - development
    
    test:
        build: .
        command: ["pytest", "--color=yes", "-vv", "--tb=short", "-l", "--capture=sys", "src"]
        env_file:
            - ./configs/api/test
        profiles:
            - testing
