version: '3.8'

services:
    api:
        build: .
        command: ["python", "-m", "src"]
        env_file:
            - ./configs/api/default
            - ./configs/api/override
        networks:
            - dev_postgres_ntwk
        depends_on:
            - dev_postgres

    tests:
        build: .
        command: ["pytest", "src"]
        env_file:
            - ./configs/api/test
        networks:
            - tests_postgres_ntwk
        depends_on:
            - tests_postgres

    dev_postgres:
        image: postgres:latest
        env_file:
            - ./configs/postgres/default
        expose:
            - 5432
        networks:
            - dev_postgres_ntwk
    
    tests_postgres:
        extends: dev_postgres
        networks:
            - tests_postgres_ntwk

networks:
    dev_postgres_ntwk:
    tests_postgres_ntwk: