version: '3.8'

services:
    api:
        build: .
        command: ["python", "-m", "src"]
        env_file:
            - ./configs/dev.env
        networks:
            - dev_postgres_ntwk
        depends_on:
            - dev_postgres

    tests:
        build: .
        env_file:
            - ./configs/test.env
        networks:
            - tests_postgres_ntwk
        depends_on:
            - tests_postgres

    dev_postgres:
        image: postgres:latest
        env_file:
            - ./configs/postgres.env
        volumes:
            - pgdata_dev:/var/lib/postgresql/data
        expose:
            - 5432
        networks:
            - dev_postgres_ntwk
    
    tests_postgres:
        extends: dev_postgres
        volumes:
            - pgdata_test:/var/lib/postgresql/data
        networks:
            - tests_postgres_ntwk

networks:
    dev_postgres_ntwk:
    tests_postgres_ntwk:

volumes:
    pgdata_dev:
    pgdata_test: